name: masterebate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  csv: ^6.0.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  http: ^1.2.2
  image_picker: ^1.0.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
