name: masterebate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  # file_picker: ^8.1.2
  file_picker: ^10.3.8
  csv: ^6.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  share_plus: ^10.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
