name: masterebate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4
  flutter: ^3.38.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  file_picker: ^10.3.8
  csv: ^6.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  share_plus: ^12.0.1     
  path_provider: ^2.1.4
  characters: ^1.4.0
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  matcher: "^0.12.17"
  test_api: "^0.7.7"

flutter:
  uses-material-design: true